version: "3.9"
services:
  db_wc_games:
    image: postgres:latest
    container_name: db_wc_games
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - prestoshat-bridge
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres

  backend_auth:
    image: prestoshat/backend_auth:1.0
    container_name: backend_auth
    restart: on-failure
    depends_on:
      - db_wc_games
    build:
      dockerfile: Dockerfile
      context: ./prestoshat-backend-auth   
      args:
        DOCKER_BUILDKIT: 1   
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_wc_games:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update      
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    networks:
      - prestoshat-bridge
    volumes:
      - .m2:/root/.m2

networks:
  prestoshat-bridge:
    driver: bridge

volumes:
  db: